# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-09 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171009_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='passphrase',
            new_name='password',
        ),
    ]
