# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-09 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='passphrase',
            field=models.CharField(default='123456', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
