# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171005_0947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Practitioner',
            new_name='Host',
        ),
    ]
