# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-05 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171005_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='title',
            field=models.CharField(blank=True, choices=[('Dr', 'Docteur')], max_length=30, null=True),
        ),
    ]
